### ISSUE TITLE
Nightlight?

### ISSUE THREAD

**Issue by zmrow** [bruhautomation/BRUH3-Home-Assistant-Configuration#1]
Curious what you're using for a nighlight?  I'm looking for a good nightlight setup.

**Comment by bruhautomation** [comment]
I use a (NodeMCU chip)[http://amzn.to/2nOaGF7} running an [adafruit neopixel ring](http://amzn.to/2oxxvLu) that I put inside of an opaque jar. 

That runs this [code](https://github.com/bruhautomation/ESP-MQTT-JSON-Digital-LEDs), but I switched the FastLED definitions to 

```
#define NUM_LEDS    12
#define DATA_PIN    5
//#define CLOCK_PIN 5
#define CHIPSET     WS2812B
#define COLOR_ORDER GRB
```

The ring runs great off of the 5V pin on the NodeMCU chip. I power the system with a 1 amp microUSB phone charger. Cheers!

**Comment by CCOSTAN** [comment]
@zmrow It's not a smart device but [SnapPower Lights](https://www.snappower.com/) are pretty kick ass.  they do one thing and do it well. ;)

**Comment by zmrow** [comment]
@CCOSTAN Ah - those are pretty awesome!  Thanks for the tip!

@bruhautomation  - Have any pics of said nightlight?  I have something started using the exact same neopixel.  :D

**Comment by bruhautomation** [comment]
@zmrow sorry for my response getting back to you. No pictures at this point, it is briefly in this video though. https://www.youtube.com/watch?v=9KI36GTgwuQ at 17:45
