### ISSUE TITLE
Can you send me the WOL command for tuen the PC off, thx!

### ISSUE THREAD

**Issue by wubin2** [bruhautomation/BRUH3-Home-Assistant-Configuration#2]
pc_off: !secret pc_off_cmd
cant see it

**Comment by CoalaJoe** [comment]
WOL stands for Wake On Lan and can't turn off your computer.
You have to use something else there. I am using Linux on my main PC, so I connect from home-assistant to my main PC and run the shutdown command.

Hope this helps.

**Comment by bruhautomation** [comment]
Sorry this is like 100 years late. The command I use is 'net rpc shutdown -f -t 0 -I pc.local.ip.address -U  windowsusername%windowspassword' I believe net RPC shutdown commands are facilitated through Samba if my memory serves me right. Cheers!

**Comment by Actpohomoc** [comment]
Thank you. Very useful.
